/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as nfTv2Sol from "./NFTv2.sol";
export type { nfTv2Sol };
