/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lowkickStarterSol from "./LowkickStarter.sol";
export type { lowkickStarterSol };
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export type { Campaign } from "./LowkickStarter.sol/Campaign";
export { Campaign__factory } from "./factories/LowkickStarter.sol/Campaign__factory";
export type { LowkickStarter } from "./LowkickStarter.sol/LowkickStarter";
export { LowkickStarter__factory } from "./factories/LowkickStarter.sol/LowkickStarter__factory";
